---

before_install:
  - "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  - "sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\""
  - "sudo apt-get update"
  - "sudo apt-get -y install docker-ce libwww-perl libjson-xs-perl"
branches:
  only:
    - "master"
env:
  global:
    - "IMAGE=irap/docker-debian-ansible:stretch"
  matrix:
    - "BID=3"
    - "BID=2"
    - "BID=1"
    - "BID=0"
language: "python"
notifications:
  email: false
python:
  - "2.7"
script:
    - "wget -O ${PWD}/run.sh https://raw.githubusercontent.com/pari-/docker-debian-ansible/master/run.sh"
    - "chmod +x ${PWD}/run.sh"
    - 'export ANSIBLE_VERSION=$(./get_ansible_version.pl ${BID}) && ./run.sh'
services: "docker"
sudo: "required"
