---

- hosts: "all"
  vars:
    docker_daemon_config_opts:
      bip: "192.168.1.5/24"
      dns:
        - "8.8.4.4"
      mtu: 1500
  roles:
    - role: "ansible-docker"
      tags:
        - "docker"
  post_tasks:
    - block:
      - include: "tests/test_docker_setup.yml"
      - block:
          - include: "tests/test_docker_tcp_listen.yml"
          - include: "tests/test_docker_http_version.yml"
        when:
          - "docker_daemon_opts | regex_search('tcp://(.*):([0-9]+)')"
      tags:
        - "tests"
