---

- name: "enforce presence of /etc/docker"
  file:
    state: "directory"
    dest: "/etc/docker"

- name: "generate configuration file"
  template:
    src: "etc/docker/daemon.json.j2"
    dest: "{{ docker_config_file }}"
  register: "docker_daemon_config"
  notify:
    - "restart docker"

- name: "allow communicating to the outside world"
  sysctl:
    name: "net.ipv4.conf.all.forwarding"
    state: "present"
    value: "{{ docker_allow_outside_world_communication }}"

- name: "integrate docker with systemd"
  template:
    src: "etc/systemd/system/docker.service.j2"
    dest: "/etc/systemd/system/docker.service"
  notify:
    - "systemctl daemon-reload"

- name: "flush handlers immediately"
  meta: "flush_handlers"

- name: "ensure the docker.service is restarted and enabled at boot"
  service:
    name: "{{ docker_service_name }}"
    state: "started"
    enabled: "yes"
    use: "systemd"
